apiVersion: v1
kind: Secret
metadata:
  name: sample-app-secret
  namespace: sample-app-namespace
type: Opaque
data:
  USERNAME: "dXNlcm5hbWU="
  PASSWORD: "cGFzc3dvcmQ="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
  namespace: sample-app-namespace
  labels:
    app: sample-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app-deployment
  template:
    metadata:
      labels:
        app: sample-app-deployment
    spec:
      containers:
      - name: nginx
        image: def4ultx/sample-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 150m
            memory: 150Mi
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /healthz
            port: liveness-port
          failureThreshold: 30
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: sample-app-config
        env:
          - name: ENV
            value: prod
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: sample-app-secret
                key: USERNAME
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: sample-app-secret
                key: PASSWORD